name: Run Gradle Tests
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Tests
        uses: eskatos/gradle-command-action@v1
        env:
          ENV: ci
        with:
          arguments: clean test codeCoverageReport sonarqube
      - name: Publish to Quay
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: quay.io/dmunro/kotlinmud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          tagging: true
      - name: Restart service
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            systemctl stop kotlinmud
            /snap/bin/docker system prune -af
            systemctl start kotlinmud